/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.lang.*;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import project.homepage2;
/**
 *
 * @author gaurav ambildhuke
 */
public class homepage extends javax.swing.JFrame {

    Connection con= null;
    PreparedStatement pre = null;
    ResultSet rs = null;
    String s;
    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        signup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        slogin = new javax.swing.JLabel();
        ssignup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slogin1 = new javax.swing.JLabel();
        studentlogin = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();
        btn_studentlogin1 = new javax.swing.JLabel();
        btn_studentlogin3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        email1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname1 = new javax.swing.JLabel();
        psw1 = new javax.swing.JLabel();
        mobile1 = new javax.swing.JLabel();
        fname1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        username2 = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        usernam = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Attendence Management System");

        slogin.setBackground(new java.awt.Color(0, 102, 102));
        slogin.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        slogin.setForeground(new java.awt.Color(255, 255, 255));
        slogin.setText("Faculty Login");
        slogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sloginMouseClicked(evt);
            }
        });

        ssignup.setBackground(new java.awt.Color(0, 51, 51));
        ssignup.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ssignup.setForeground(new java.awt.Color(255, 255, 255));
        ssignup.setText("Sign Up");
        ssignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssignupMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\gaurav ambildhuke\\Downloads\\icons8-login (1).png")); // NOI18N
        jLabel2.setText("jLabel2");

        slogin1.setBackground(new java.awt.Color(0, 102, 102));
        slogin1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        slogin1.setForeground(new java.awt.Color(255, 255, 255));
        slogin1.setText("Student Login");
        slogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slogin1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(ssignup)
                        .addGap(30, 30, 30)
                        .addComponent(slogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addGap(0, 468, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(slogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(967, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(slogin))
                            .addComponent(ssignup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 153, Short.MAX_VALUE)
                    .addComponent(slogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        studentlogin.setBackground(new java.awt.Color(255, 153, 102));

        btn_login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 153, 0));
        btn_login.setText("Log In");
        btn_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 0), null, null));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_studentlogin1.setBackground(new java.awt.Color(0, 102, 102));
        btn_studentlogin1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_studentlogin1.setForeground(new java.awt.Color(255, 255, 255));
        btn_studentlogin1.setText("Password");
        btn_studentlogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studentlogin1MouseClicked(evt);
            }
        });

        btn_studentlogin3.setBackground(new java.awt.Color(0, 102, 102));
        btn_studentlogin3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btn_studentlogin3.setForeground(new java.awt.Color(255, 255, 255));
        btn_studentlogin3.setText("Username");
        btn_studentlogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studentlogin3MouseClicked(evt);
            }
        });

        username.setForeground(new java.awt.Color(255, 153, 102));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setForeground(new java.awt.Color(255, 102, 51));

        jLabel5.setBackground(new java.awt.Color(255, 51, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\gaurav ambildhuke\\Downloads\\icons8-user (1).png")); // NOI18N

        javax.swing.GroupLayout studentloginLayout = new javax.swing.GroupLayout(studentlogin);
        studentlogin.setLayout(studentloginLayout);
        studentloginLayout.setHorizontalGroup(
            studentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentloginLayout.createSequentialGroup()
                .addGroup(studentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentloginLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(studentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                    .addGroup(studentloginLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentloginLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(studentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_studentlogin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_studentlogin1)
                .addGap(154, 154, 154))
        );
        studentloginLayout.setVerticalGroup(
            studentloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentloginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_studentlogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_studentlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_login)
                .addGap(84, 84, 84))
        );

        signup.setBackground(new java.awt.Color(44, 62, 80));

        email1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        email1.setForeground(new java.awt.Color(248, 148, 6));
        email1.setText("Email Id");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 148, 6));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign Up");

        lname1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lname1.setForeground(new java.awt.Color(248, 148, 6));
        lname1.setText("Last Name");

        psw1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        psw1.setForeground(new java.awt.Color(248, 148, 6));
        psw1.setText("Password");

        mobile1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        mobile1.setForeground(new java.awt.Color(248, 148, 6));
        mobile1.setText("Mobile No");

        fname1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        fname1.setForeground(new java.awt.Color(248, 148, 6));
        fname1.setText("First Name");

        email.setBackground(new java.awt.Color(204, 255, 204));
        email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(248, 148, 6));
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        fname.setBackground(new java.awt.Color(204, 255, 204));
        fname.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(248, 148, 6));
        fname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fname.setName(""); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        lname.setBackground(new java.awt.Color(204, 255, 204));
        lname.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 204, 0));
        lname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        username2.setBackground(new java.awt.Color(204, 255, 204));
        username2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        username2.setForeground(new java.awt.Color(248, 148, 6));
        username2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username2ActionPerformed(evt);
            }
        });

        mobile.setBackground(new java.awt.Color(204, 255, 204));
        mobile.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        mobile.setForeground(new java.awt.Color(248, 148, 6));
        mobile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        btn_signup.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(248, 148, 6));
        btn_signup.setText("Submit Details");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });

        usernam.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        usernam.setForeground(new java.awt.Color(248, 148, 6));
        usernam.setText("Username");

        psw.setBackground(new java.awt.Color(204, 255, 204));
        psw.setForeground(new java.awt.Color(248, 148, 6));
        psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupLayout = new javax.swing.GroupLayout(signup);
        signup.setLayout(signupLayout);
        signupLayout.setHorizontalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(signupLayout.createSequentialGroup()
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(usernam, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(psw1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(mobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupLayout.setVerticalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psw1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(btn_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("add photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sloginMouseClicked
        // TODO add your handling code here:
       studentlogin.setVisible(true);
       signup.setVisible(false);
       
      
        
        
    }//GEN-LAST:event_sloginMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String user=username.getText();
        String pasword=password.getText();
        username.setText("");
        password.setText("");
        con=MySqlConnect.connectDB();
          homepage2 hp = new homepage2(user,pasword);
                
        String sql = "Select * from stud where id=? and fname=?";
        try{
            pre = con.prepareStatement(sql);
            pre.setString(1,user);
            pre.setString(2,pasword);
            rs=pre.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"Welcome user");
                
                hp.setVisible(true);
          
             }
            else{
                JOptionPane.showMessageDialog(null,"Invalid username or password","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_studentlogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studentlogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_studentlogin1MouseClicked

    private void btn_studentlogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studentlogin3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_studentlogin3MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username2ActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        
        String fnam    = fname.getText();
        String lnam    = lname.getText();
        String userna = username2.getText();
        String pass = psw.getText();
        String mob   = mobile.getText();
        String mail     = email.getText();
        
        try{
            
         
            con=MySqlConnect.connectDB();
            pre=con.prepareStatement("insert into stud values(?,?,?,?,?,?)");
            pre.setString(1, userna);
            pre.setString(2, fnam);
            pre.setString(3, lnam);
            pre.setString(4, pass);
            pre.setString(5, mob);
            pre.setString(6, mail);
            pre.executeUpdate();
            JOptionPane.showMessageDialog(this,"You have succesfully signed up.");
            refreshField();
            
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    private void pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_pswActionPerformed

    private void ssignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssignupMouseClicked
        // TODO add your handling code here:
        signup.setVisible(true);
        studentlogin.setVisible(false);
    }//GEN-LAST:event_ssignupMouseClicked

    private void slogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_slogin1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        JFileChooser filechooser = new JFileChooser();
        filechooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE","jpg","gif","jpg","png");
        filechooser.addChoosableFileFilter(filter);
        int result=filechooser.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile = filechooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            
            s = path;
        }
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        con=MySqlConnect.connectDB();
        String sql="insert into stud(image) values(?)";
        pre=con.prepareStatement(sql);
        FileInputStream is = new FileInputStream(new File(s)) ;
        pre.setBlob(1,is);
        pre.executeUpdate();
        JOptionPane.showMessageDialog(null,"data Inserted");
    }//GEN-LAST:event_jButton2ActionPerformed
    catch(Exception e){
        e.printStackTrace();
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel btn_studentlogin1;
    private javax.swing.JLabel btn_studentlogin3;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fname1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lname1;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobile1;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField psw;
    private javax.swing.JLabel psw1;
    private javax.swing.JPanel signup;
    private javax.swing.JLabel slogin;
    private javax.swing.JLabel slogin1;
    private javax.swing.JLabel ssignup;
    private javax.swing.JPanel studentlogin;
    private javax.swing.JLabel usernam;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username2;
    // End of variables declaration//GEN-END:variables

   /* private  String passwordCheck(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //password must be atleast of 6characters
    //password should contain atleast one uppercase
    //password should contain atleast one numeric character
    //no symbols are allowed
        String result;
        result = "invalid Password";
        int x;
        int length=0;
        int capCount=0;
        int numCount=0;
        for(x=0;x<text.length();x++){
            if((text.charAt(x)>=47&&text.charAt(x)<=58)||(text.charAt(x)>=64&&text.charAt(x)<=91)&&(text.charAt(x)>=97&&text.charAt(x)<=122)){
                
            }
            else{
                result ="password contains invalid character!";
            }
            if(text.charAt(x)>47||text.charAt(x)<58){
                numCount++;
            }
            if(text.charAt(x)>64||text.charAt(x)<91){
                capCount++;
            }
            length=(x+1);
    }
        
        if(numCount<2){
            result = "not enough numerical alphabets";
                }
        if(capCount<1){
            result="atleast one uppercase character needed";
        }
        if(length<6){
            result="password must be of atleast 6 characters";
        }
        return result;
    }*/

    private void refreshField() {
         //To change body of generated methods, choose Tools | Templates.
        fname.setText("");
        lname.setText("");
        psw.setText("");
        username2.setText("");
        mobile.setText("");
        email.setText("");
    }
}
  
